### PR TITLE
Always use CDN and latest-stable in buildArch.sh

### PR DESCRIPTION
**Pull request by maxwell-k**
Two minor changes to buildArch.sh:

- to always pull packages via the CDN and
- to use latest-stable consistently

### CODE REVIEW

**Comment by carbonatedcaffeine** [comment]
Looks good corbin...

**Comment by corbinlc** [comment]
Thanks.  When I next build the Alpine image, it will have this change.  I will close the issue after I do so.

**Comment by maxwell-k** [comment]
@corbinlc sorry I think because I had "Fixes #10" in a commit message the issue was closed when you merged the PR. Unfortunately I don't have permissions to reopen it.

From [IRC](https://dev.alpinelinux.org/irclogs/%23alpine-devel-2019-05.log) I gather Alpine Linux will release 3.9.4 in the next few days, in case that might be a prompt to build the image.

And also thank you, I think this is a great project!

**Comment by carbonatedcaffeine** [comment]
Would you like me to build the image's corbin?

**Pull request merged**
